- name: Deploy to GitHub Pages
  runs-on: ubuntu-latest
  on: pull_request
  jobs:
  build:
   name: Build the React app 
  runs-on: ubuntu-latest 
  steps:
  uses: actions/checkout@v3
- name: Setup node
  uses: actions/setup-node@v4
- name: Installs required npm dependencies
  run: npm install
  cache-dependency-path: './package-lock.json'
- name: Build the React app
  uses: actions/checkout@v3
  with: git@github.com:shreelata/repo.git
  run: npm run build
- name: Deploy to GitHub Pages
  uses: gh-pages -d build
  publish-location: 'gh-pages'
  publish-source: 'build'
  publish-repository: 'client'
  publish-branch: 'master'
  publish-url : 'https://shreelata.github.io/client'
